replicaCount: 2

image:
  repository: 729859598223.dkr.ecr.ap-south-1.amazonaws.com/nginx
  tag: "1.2.18"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

gateway:
  enabled: true

  name: sample-app

  selector:
    istio: ingressgateway

  host: nginx.sundeepdevops.com

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 250m
    memory: 256Mi


  

