apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: onlineboutique
  namespace: argocd

spec:

  goTemplate: true

  generators:

    - list:

        elements:

          - environment: dev
            clusterName: dev-cluster
            region: us-east-1

          - environment: stage
            clusterName: stage-cluster
            region: us-east-1

          - environment: prod
            clusterName: prod-cluster
            region: us-east-1


  template:

    metadata:
      name: '{{.clusterName}}'

    spec:

      project: default

      source:

        repoURL: https://github.com/YOUR-ORG/YOUR-GITOPS-REPO.git

        targetRevision: main

        path: onlineboutique

        helm:

          valueFiles:
            - 'values-{{.environment}}.yaml'


      destination:

        name: '{{.clusterName}}'

        namespace: onlineboutique


      syncPolicy:

        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true