apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: applications
  namespace: {{ .Values.namespace }}

spec:

  generators:

    - matrix:

        generators:

          - git:

              repoURL: {{ .Values.repository.url }} # https://github.com/sundeepreddy123/pipelines.git

              revision: {{ .Values.repository.targetRevision }} # main

              directories:

                - path: {{ .Values.applicationSet.applicationsPath }} # applications/*

          - clusters: {}

  template:

    metadata:

      name: '{{path.basename}}-{{name}}' # This will make the application name as <directory-name>-<cluster-name>.

    spec:

      project: {{ .Values.project.name }} # ap-south-1

      source:

        repoURL: {{ .Values.repository.url }} # https://github.com/sundeepreddy123/pipelines.git

        targetRevision: {{ .Values.repository.targetRevision }} # main

        path: '{{path}}' # applications/<app-name>

        helm:

          valueFiles:

            - values-{{name}}.yaml # This will make the values file as values-<cluster-name>.yaml.

      destination:

        server: '{{server}}' # This will make the destination server as <cluster-server>.

        namespace: '{{path.basename}}' # This will make the destination namespace as <directory-name>.

      syncPolicy:

        automated:

          prune: true

          selfHeal: true

        syncOptions:

          - CreateNamespace=true