apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: applications
  namespace: {{ .Values.namespace }}

spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: {{ .Values.repository.url }}
              revision: {{ .Values.repository.targetRevision }}
              directories:
                - path: {{ .Values.applicationSet.applicationsPath }}

          - clusters: 
              selector:
                matchLabels:
                  cluster-type: workload

  template:
    metadata:
      name: '{{ "{{path.basename}}" }}-{{ "{{name}}" }}'

    spec:
      project: {{ .Values.project.name }}

      source:
        repoURL: {{ .Values.repository.url }}
        targetRevision: {{ .Values.repository.targetRevision }}
        path: '{{ "{{path}}" }}'

        helm:
          valueFiles:
            - values-{{ "{{name}}" }}.yaml

      destination:
        server: '{{ "{{server}}" }}'
        namespace: '{{ "{{path.basename}}" }}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true