{{- range .Values.clusters }}

apiVersion: v1

kind: Secret

metadata:

  name: cluster-{{ .name }}

  namespace: {{ $.Values.namespace }}

  labels:

    argocd.argoproj.io/secret-type: cluster

type: Opaque

stringData:

  name: {{ .name }}

  server: {{ .server }}

  config: |
    {
      "tlsClientConfig": {
        "insecure": false
      }
    }

---

{{- end }}