## This will makes you register all give clusters in ArgoCD. You can add more clusters in values.yaml file.
{{- range .Values.clusters }}

---
apiVersion: v1
kind: Secret

metadata:
  name: cluster-{{ .name }}
  namespace: {{ $.Values.namespace }}

  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: {{ .labels.environment }}

type: Opaque

stringData:

  name: {{ .name }}

  server: {{ .server }}

  config: |
    {
      "awsAuthConfig": {
        "clusterName": "{{ .clusterName }}",
        "roleARN": "{{ $.Values.serviceAccount.iamRoleArn }}"
      },
      "tlsClientConfig": {
        "insecure": false
      }
    }

{{- end }}