apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: github-repository
  namespace: {{ .Values.namespace }}

spec:

  refreshInterval: 1h

  secretStoreRef:
    name: {{ .Values.clusterSecretStore.name }}
    kind: ClusterSecretStore

  target:

    name: github-repository

    creationPolicy: Owner

    template:

      type: Opaque

      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository

      data:

        type: git

        url: "{{ .Values.repository.url }}"

        username: "{{ `{{ .username }}` }}"

        password: "{{ `{{ .token }}` }}"

  data:

    - secretKey: username
      remoteRef:
        key: {{ .Values.githubSecret.awsSecretName }}
        property: username

    - secretKey: token
      remoteRef:
        key: {{ .Values.githubSecret.awsSecretName }}
        property: token