{{- $gatewayCreated := false }}

{{- range .Values.services }}

{{- if and .gateway.enabled (not $gatewayCreated) }}

---
apiVersion: networking.istio.io/v1
kind: Gateway

metadata:
  name: {{ $.Release.Name }}-gateway
  namespace: {{ $.Values.namespace }}

spec:
  selector:
    istio: istio-ingressgateway

  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP

      hosts:
{{- range $.Values.services }}
{{- if .gateway.enabled }}
        - {{ .gateway.host | quote }}
{{- end }}
{{- end }}

{{- $gatewayCreated = true }}

{{- end }}

{{- end }}