{{- range .Values.services }}
---
apiVersion: v1
kind: Service

metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}

  labels:
    app: {{ .name }}

spec:

  type: {{ .service.type }}

  selector:
    app: {{ .name }}

  ports:
    - name: {{ .service.portName }}
      port: {{ .service.port }}
      targetPort: {{ .service.targetPort }}
      protocol: TCP

{{- end }}