namespace: argocd

serviceAccount:
  name: argocd
  iamRoleArn: arn:aws:iam::<ACCOUNT_ID>:role/argocd-management-role

repository:
  url: https://github.com/sundeepreddy123/pipelines.git
  targetRevision: main

project:
  name: platform
  description: Enterprise GitOps Platform

aws:
  region: us-east-1

clusterSecretStore:
  name: aws-secretsmanager

githubSecret:
  awsSecretName: argocd
  kubernetesSecretName: github-repository

applicationSet:
  applicationsPath: applications/*
  namespace: default

clusters:
  matchLabels:
    gitops: managed

