{{- if .Values.gateway.enabled }}

apiVersion: networking.istio.io/v1
kind: Gateway

metadata:
  name: {{ .Values.gateway.name }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  selector:
{{ toYaml .Values.gateway.selector | indent 4 }}

  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - {{ .Values.gateway.host }}

  {{- if .Values.gateway.tls.enabled }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ .Values.gateway.tls.credentialName }}
    hosts:
      {{- range .Values.gateway.tls.hosts }}
      - {{ . }}
      {{- end }}
  {{- end }}

{{- end }}