{{- if .Values.gateway.enabled }}

apiVersion: networking.istio.io/v1
kind: Gateway

metadata:
  name: {{ .Values.gateway.name }}

spec:

  selector:
{{ toYaml .Values.gateway.selector | indent 4 }}

  servers:

  - port:
      number: 80
      name: http
      protocol: HTTP
    
    hosts:
      - {{ .Values.gateway.host }}
      
  - port:
      number: 443
      name: https
      protocol: HTTPS
    
    tls:
      mode: SIMPLE
      credentialName: webapp-cert

    hosts:
      - {{ .Values.gateway.host }}

{{- end }}