name: Build and push to ECR
on:
  push:
    branches:
      - main
  
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ECR_REPOSITORY: nginx
  APP_VERSION: 1.0.0

jobs:
  build:

    runs-on: ubuntu-latest
    environment:
      name: AWS-credentials
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }}:${{ env.APP_VERSION }} ./app

      - name: Tag Docker image
        run: |
          docker tag ${{ env.ECR_REPOSITORY }}:${{ env.APP_VERSION }} ${{ env.ECR_REPOSITORY }}:${{ env.APP_VERSION }}
        
      - name: Install Trivy scanner
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          trivy --version
          trivy image --exit-code 1 --severity HIGH,CRITICAL ${{ env.ECR_REPOSITORY }}:${{ env.APP_VERSION }}

      - name: Push Docker image to ECR
        run: |
          docker push ${{ env.ECR_REPOSITORY }}:${{ env.APP_VERSION }}